# Generated by Django 6.0.7 on 2026-09-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_timetable_timetableperiod_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timetable',
            name='unique_class_academic_year_timetable',
        ),
        migrations.AddField(
            model_name='timetable',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timetable',
            name='timetable_type',
            field=models.CharField(choices=[('PERMANENT', 'Permanent'), ('TEMPORARY', 'Temporary')], default='PERMANENT', max_length=20),
        ),
        migrations.AddField(
            model_name='timetable',
            name='valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.UniqueConstraint(fields=('academic_class', 'academic_year', 'timetable_type'), name='unique_class_academic_year_timetable_type'),
        ),
    ]
