# Generated by Django 6.0.7 on 2026-08-27 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0005_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=100)),
                ('service_uuid', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MAINTENANCE', 'Maintenance')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['device_name'],
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('classroom_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('room_no', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='devices.device')),
            ],
            options={
                'verbose_name': 'Classroom',
                'verbose_name_plural': 'Classrooms',
                'ordering': ['room_no'],
            },
        ),
        migrations.CreateModel(
            name='ClassDevice',
            fields=[
                ('class_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('class_data', models.CharField(help_text='Class/service data associated with the ESP32/class', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_devices', to='academics.academicclass')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_devices', to='devices.classroom')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_devices', to='devices.device')),
            ],
            options={
                'verbose_name': 'Class Device',
                'verbose_name_plural': 'Class Devices',
                'ordering': ['academic_class__class_code'],
                'constraints': [models.UniqueConstraint(fields=('academic_class', 'classroom'), name='unique_academic_class_classroom')],
            },
        ),
    ]
