# Generated by Django 6.0.7 on 2026-08-27 21:31

from django.db import migrations


def update_classroom_data(apps, schema_editor):
    Classroom = apps.get_model('devices', 'Classroom')

    # Required classroom rooms
    required_rooms = [
        # MCA
        "Room 101",
        "Room 102",
        "Room 103",
        "Room 104",
        # BCA
        "Room 105",
        "Room 106",
        "Room 107",
        "Room 108",
        "Room 109",
        "Room 110",
        "Room 111",
        "Room 112",
        # MBA
        "Room 201",
        "Room 202",
        "Room 203",
        "Room 204",
        # BBA
        "Room 205",
        "Room 206",
        "Room 207",
        "Room 208",
        "Room 209",
        "Room 210",
        "Room 211",
        "Room 212",
    ]

    # Map of existing classroom IDs to new room numbers
    # We'll update existing records first to preserve IDs and references
    existing_classrooms = list(Classroom.objects.all().order_by('classroom_id'))

    # Rooms to keep/update (first 6 existing match required rooms)
    rooms_to_update = [
        "Room 101",  # ID 3
        "Room 102",  # ID 4
        "Room 103",  # ID 5
        "Room 201",  # ID 6
        "Room 202",  # ID 7
        "Room 203",  # ID 8
    ]

    # Update existing classrooms that match
    for i, classroom in enumerate(existing_classrooms[:6]):
        if i < len(rooms_to_update):
            classroom.room_no = rooms_to_update[i]
            classroom.save()

    # Delete Lab rooms (IDs 9, 10, 11) since they're not in required list
    # and no ClassDevice references exist
    Classroom.objects.filter(room_no__in=["Lab 1", "Lab 2", "Lab 3"]).delete()

    # Create new classrooms for remaining required rooms
    existing_rooms = set(Classroom.objects.values_list('room_no', flat=True))
    for room in required_rooms:
        if room not in existing_rooms:
            Classroom.objects.create(room_no=room, device=None)


def reverse_classroom_data(apps, schema_editor):
    Classroom = apps.get_model('devices', 'Classroom')

    # Restore original state
    required_rooms = [
        "Room 101", "Room 102", "Room 103", "Room 104",
        "Room 105", "Room 106", "Room 107", "Room 108",
        "Room 109", "Room 110", "Room 111", "Room 112",
        "Room 201", "Room 202", "Room 203", "Room 204",
        "Room 205", "Room 206", "Room 207", "Room 208",
        "Room 209", "Room 210", "Room 211", "Room 212",
    ]

    # Delete all required rooms
    Classroom.objects.filter(room_no__in=required_rooms).delete()

    # Recreate original rooms
    original_rooms = [
        ("Room 101", None),
        ("Room 102", None),
        ("Room 103", None),
        ("Room 201", None),
        ("Room 202", None),
        ("Room 203", None),
        ("Lab 1", None),
        ("Lab 2", None),
        ("Lab 3", None),
    ]
    for room_no, device in original_rooms:
        Classroom.objects.create(room_no=room_no, device=device)


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_classroom_device'),
    ]

    operations = [
        migrations.RunPython(update_classroom_data, reverse_classroom_data),
    ]