# Generated by Django 6.0.7 on 2026-08-28 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_fix_classdevice_fk_names'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='classdevice',
            name='unique_class_device_assignment',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='device',
        ),
        migrations.RemoveField(
            model_name='classdevice',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='classdevice',
            name='course',
        ),
        migrations.RemoveField(
            model_name='classdevice',
            name='department',
        ),
        migrations.RemoveField(
            model_name='classdevice',
            name='division',
        ),
        migrations.RemoveField(
            model_name='classdevice',
            name='semester',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
        migrations.DeleteModel(
            name='ClassDevice',
        ),
    ]