# Generated by Django 6.0.7 on 2026-08-28 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0005_subject'),
        ('devices', '0007_remove_classdevice_unique_class_device_assignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=100)),
                ('service_uuid', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MAINTENANCE', 'Maintenance')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['device_name'],
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('classroom_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('room_no', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='devices.device')),
            ],
            options={
                'verbose_name': 'Classroom',
                'verbose_name_plural': 'Classrooms',
                'ordering': ['room_no'],
            },
        ),
        migrations.CreateModel(
            name='ClassDevice',
            fields=[
                ('class_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('class_data', models.CharField(help_text='Class/service data associated with the ESP32/class', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_devices', to='academics.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_devices', to='academics.department')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_devices', to='academics.academicclass')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_devices', to='academics.semester')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_devices', to='devices.classroom')),
            ],
            options={
                'verbose_name': 'Class Device',
                'verbose_name_plural': 'Class Devices',
                'ordering': ['department__name', 'course__name', 'semester__semester_number', 'division__division'],
                'constraints': [models.UniqueConstraint(fields=('department', 'course', 'semester', 'division', 'classroom'), name='unique_class_device_assignment')],
            },
        ),
    ]
