# Generated by Django 6.0.7 on 2026-08-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='room_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
