# Generated by Django 6.0.7 on 2026-08-30 09:55

from django.db import migrations


def populate_classrooms(apps, schema_editor):
    Classroom = apps.get_model('devices', 'Classroom')
    # Add initial classroom records
    rooms = ['101', '102', '103', '104', '201', '202', '301', '302']
    for room in rooms:
        # Avoid duplicates
        if not Classroom.objects.filter(room_no=room).exists():
            Classroom.objects.create(room_no=room)


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_alter_classroom_room_no'),
    ]

    operations = [
        migrations.RunPython(populate_classrooms),
    ]