# Generated by Django 6.0.7 on 2026-08-30

from django.db import migrations


REQUIRED_ROOMS = [
    "101", "102", "103", "104",
    "201", "202", "203", "204",
    "301", "302", "303", "304", "305", "306", "307", "308",
    "401", "402", "403", "404", "405", "406", "407", "408",
]


def add_required_classrooms(apps, schema_editor):
    Classroom = apps.get_model("devices", "Classroom")
    for room_no in REQUIRED_ROOMS:
        # Existing rooms (and any device assignments) are left untouched.
        Classroom.objects.get_or_create(room_no=room_no)


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0010_populate_classrooms"),
    ]

    operations = [
        migrations.RunPython(add_required_classrooms, migrations.RunPython.noop),
    ]
