# Generated by Django 6.0.7 on 2026-08-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0011_add_required_classroom_rooms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="service_uuid",
            field=models.CharField(max_length=50),
        ),
    ]
